FROM phusion/baseimage:0.11

WORKDIR /opt/app

COPY fuzzer /opt/app/fuzzer/

COPY parse /opt/app/parse/

COPY replay /opt/app/replay/

COPY targets /opt/app/targets/

COPY fuzz_opcua_server.py requirements.txt /opt/app/

RUN install_clean build-essential python3 python3-dev python3-setuptools python3-wheel python3-pip git lsof

RUN pip3 install -U pip

RUN pip3 install -r requirements.txt
